name: Build & Publish

on:
  # Publish to TestPyPI for any tag that looks like a pre-release (e.g., v0.3.0-rc1)
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Versioneer needs tags
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install build deps
        run: python -m pip install --upgrade build
      - name: Build sdist+wheel
        run: python -m build
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/*

  publish-testpypi:
    needs: build
    runs-on: ubuntu-latest
    environment: testpypi
    permissions:
      id-token: write   # REQUIRED for Trusted Publishing
      contents: read
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist
      - name: Publish to TestPyPI (Trusted Publishing)
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
