name: Run tests (CPU)

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        environment-file: environment.yml
        activate-environment: bamojax-env

    - name: Install jaxkern fork from GitHub
      run: pip install git+https://github.com/UncertaintyInComplexSystems/JaxKern.git
      shell: bash -l {0}

    - name: Install bamojax in editable mode
      run: pip install -e .
      shell: bash -l {0}

    - name: Run tests
      run: |
        pytest tests/
      shell: bash -l {0}  # Correct login shell so conda env is activated
